parameters:
    database_driver: pdo_mysql
    database_host: 172.16.218.61
    database_port: '9969'
    database_name: finanzas
    database_user: adam_benaim
    database_password: cambiar4367
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 48fcd2ac0d33d75b5698585506f944b21494d441
    database_path: null
