parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: ''
    database_name: potool
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 48fcd2ac0d33d75b5698585506f944b21494d441
    database_path: null
