potool\conciliationBundle\Entity\Acquirer:
    type: entity
    table: acquirer
    fields:
        acquirerPk:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: acquirer_PK
            generator:
                strategy: IDENTITY
        acquirerName:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: acquirer_name
        acquirerFkCountryPk:
            type: integer
            unsigned: false
            nullable: true
            column: acquirer_FK_country_PK
    lifecycleCallbacks: {  }
